config/routes.rb
Agiledme::Application.routes.draw do

  resources :epics do
    member do
      get :finish
    end
  end

  resources :labels

  resources :projects do
    member do
      get :join, :leave, :overview, :reports, :sprint, :import_pivotal_csv, :show_more_items
      post :upload_pivotal_csv, :search, :update_velocity_trend_report, :update_story_trend_report, :update_burndown_chart
    end
    resources :project_users
    resources :stories do
      member do
        get :start, :finish, :deliver, :accept, :reject, :restart, :estimate, :un_start, :un_finish, :un_deliver
        put :update_category_and_priority
      end
      resources :story_histories

    end
    resources :epics, :controller => :stories
    resources :features, :controller => :stories
    resources :bugs, :controller => :stories
    resources :chores, :controller => :stories
  end

  resources :story_attachments do
    member do
      get :download_attachment
    end
  end

  devise_for :users, :controllers => {:registrations => 'users/registrations'}

  root :to => "dashboard#index"

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  require 'csv'
  before_filter :find_project, :except => :create

  def search
    @search_term = params[:search_term]
    @scope = params[:scope]
    respond_to do |format|
      if @search_term.present? and @search_term.length > 2
        if @scope.eql?("sprint")
          @stories = @project.stories(:include => [:comments, :tasks]).where(:category => "current")
        else
          @stories = @project.stories(:include => [:comments, :tasks])
        end

        if @stories.present?
          if is_search_by_owner?
            @search_results = get_items_for_owner(@search_term.split(':')[1])
          elsif is_search_by_label?
            @search_results = get_items_for_label(@search_term.split(':')[1])
          else
            @search_results = get_items_for(@search_term)

            owner_results = get_items_for_owner(@search_term)
            label_results = get_items_for_label(@search_term)
            comment_results = get_items_for_comments(@search_term)
            task_results = get_items_for_tasks(@search_term)

            if @search_results.present?
              if owner_results.present?
                @search_results = @search_results + owner_results
              end
            else
              @search_results = get_items_for_owner(@search_term)
            end

            if @search_results.present?
              if label_results.present?
                @search_results = @search_results + label_results
              end
            else
              @search_results = label_results
            end

            if @search_results.present?
              if comment_results.present?
                @search_results = @search_results + comment_results
              end
            else
              @search_results = comment_results
            end

            if @search_results.present?
              if task_results.present?
                @search_results = @search_results + task_results
              end
            else
              @search_results = task_results
            end
          end
        else
          @search_results = nil
        end
      else
        @error = "Please enter minimum 3 letters to search!"
      end
      format.js
    end
  end

  def import_pivotal_csv
  end

  def upload_pivotal_csv

    respond_to do |format|
      if params[:file].present?
        old_items = @project.stories.count
        file = IO.read(params[:file].tempfile.path)

        CSV.new(file, :headers => true).each do |row|
          csv_type = row['Story Type']
          #importing release is not supported as of today (22 March 2012)
          if !csv_type.eql?("release")
            story = create_story(row)
            import_labels(row, story)
            import_comments(row, story)
            import_tasks(row, story)
            story.save!
          end
        end

        new_items = @project.stories.count
        flash[:notice] = "Successfully imported #{new_items - old_items} items!!"
        format.html { render :template => 'projects/import_pivotal_csv' }
      else
        flash[:notice] = "ERROR!! Please select a CSV to import!!"
        format.html { render :template => 'projects/import_pivotal_csv' }
      end
    end
  end

  def get_status(csv_task_status)
    csv_task_status.eql?("completed") ? "finished" : "new"
  end

  def overview
    @project_users = @project.project_users.page(params[:page]).per(10)

    respond_to do |format|
      format.html
      format.xml { render :xml => @project }
    end
  end

  def reports
    @sprints_select = @project.no_of_sprints_passed.times.collect { |v| (v + 1) }
    @sprint = @project.current_sprint

    @from_sprint = @project.default_from_sprint
    @to_sprint = @project.no_of_sprints_passed

    @sprints_from_to = (@from_sprint..@to_sprint.to_i).to_a

    @chores_trend = @project.chores_trend
    @bugs_trend = @project.bugs_trend
    @features_trend = @project.features_trend
    @velocity_trend = @project.velocity_trend

    @actual_burndown_chart_data_series = @project.actual_burndown_data_series
    @idle_burndown_chart_data_series = @project.idle_burndown_data_series
    @burndown_chart_point_start = @project.current_sprint_start_date.at_midnight.to_i * 1000
    @burndown_chart_point_interval = 1.day * 1000

  end

  def update_velocity_trend_report
    from_sprint = params[:from_sprint].to_i
    to_sprint = params[:to_sprint].to_i
    @from_sprint = from_sprint
    @to_sprint = to_sprint
    @velocity_trend = @project.velocity_trend_between_sprints(from_sprint, to_sprint)

    respond_to do |format|
      format.js
    end
  end

  def update_burndown_chart
    @sprint = params[:sprint].to_i

    @actual_burndown_chart_data_series = @project.actual_burndown_data_series_for_sprint(@sprint)
    @idle_burndown_chart_data_series = @project.idle_burndown_data_series_for_sprint(@sprint)
    @burndown_chart_point_start = @project.beginning_of_sprint(@sprint).at_midnight.to_i * 1000
    @burndown_chart_point_interval = 1.day * 1000

    respond_to do |format|
      format.js
    end
  end

  def update_story_trend_report
    from_sprint = params[:from_sprint].to_i
    to_sprint = params[:to_sprint].to_i

    @from_sprint = from_sprint
    @to_sprint = to_sprint
    @sprints_from_to = []
    (@from_sprint..@to_sprint.to_i).each { |v| @sprints_from_to << v }

    @chores_trend = @project.stories_trend_between_sprints(from_sprint, to_sprint, 'Chore')
    @bugs_trend = @project.stories_trend_between_sprints(from_sprint, to_sprint, 'Bug')
    @features_trend = @project.stories_trend_between_sprints(from_sprint, to_sprint, 'Feature')

    respond_to do |format|
      format.js
    end

  end

  def sprint
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @project }
    end
  end

  def show
    @project_users = @project.active_users
    respond_to do |format|
      format.html
      format.xml { render :xml => @project }
    end
  end

  def show_more_items
    @category = params[:category]
    @stories_to_append = @project.stories.where(:category => params[:category]).limit(15).offset(params[:offset])
    respond_to do |format|
      format.js
    end
  end

  def edit
  end

  def create
    @project = Project.new(params[:project])
    @project.project_users << ProjectUser.new(:user_id => current_user.id, :project_id => @project.id, :active => true, :role => "owner")
    respond_to do |format|
      if @project.save
        format.js
      else
        format.xml { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to overview_project_path(@project), :notice => 'Project was successfully updated.' }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def join
    current_user.join_project(@project)
    respond_to do |format|
      format.js
    end
  end

  def leave
    current_user.leave_project(@project)
    respond_to do |format|
      format.html { redirect_to root_path, :notice => 'You left the project.' }
    end
  end

  def destroy

    @project.destroy

    respond_to do |format|
      format.html { redirect_to root_path, :notice => 'You deleted the project .' }
      format.xml { head :ok }
    end
  end

  private

  def find_project
    @project = current_user.projects.find(params[:id])
  end

  def create_story(row)
    csv_state = row['Current State']
    csv_category = parse_category(csv_state)
    csv_type = row['Story Type'].camelize
    story = Story.new(:project_id => @project.id,
                      :title => row['Story'],
                      :description => row['Description'],
                      :requester => row['Requested By'].present? ? get_existing_or_current_user(row['Requested By']) : current_user.id,
                      :status => (csv_state.eql?('unstarted') || csv_state.eql?('unscheduled')) ? "not_yet_started" : row['Current State'],
                      :category => csv_category,
                      :estimate => (csv_type.eql?("Feature") and row['Estimate'].present?) ? row['Estimate'].to_i : -1,
                      :priority => get_max_priority_for_category(csv_category) + 1)


    story.type = csv_type

    if row['Owned By'].present?
      story.owner = get_existing_or_current_user(row['Owned By'])
    end

    if !csv_state.eql?("unstarted")
      if csv_state.eql?("accepted")
        story.started_at = Time.now
        story.finished_at = Time.now
        story.delivered_at = Time.now
        story.accepted_at = Time.now
      elsif csv_state.eql?("rejected")
        story.started_at = Time.now
        story.finished_at = Time.now
        story.delivered_at = Time.now
        story.rejected_at = Time.now
      elsif csv_state.eql?("delivered")
        story.started_at = Time.now
        story.finished_at = Time.now
        story.delivered_at = Time.now
      elsif csv_state.eql?("finished")
        story.started_at = Time.now
        story.finished_at = Time.now
      elsif csv_state.eql?("started")
        story.started_at = Time.now
      end
    end
    story
  end

  def get_existing_or_current_user(user_name)
    User.find_by_name(user_name).present? ? User.find_by_name(user_name).id : current_user.id
  end

  def parse_category(state)
    if state.eql?('accepted')
      "done"
    elsif (state.eql?('unstarted') || state.eql?('unscheduled'))
      "icebox"
    else
      "current"
    end
  end

  def get_max_priority_for_category(category)
    max_priority = @project.stories.where(:category => category).maximum(:priority)
    max_priority.present? ? max_priority : 0
  end

  def import_labels(row, story)
    if row['Labels'].present?

app/helpers/projects_helper.rb
module ProjectsHelper

  def link_to_add_task_fields(name, f, association, item_id)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render("stories/"+association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, ("add_task_fields(this, '#{association.to_s.singularize}', '#{escape_javascript(fields)}')"), :id => "#{item_id}_add_task")
  end

  def link_to_add_comment_fields(name, f, association, item_id)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render("stories/"+association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, ("add_comment_fields(this, '#{association.to_s.singularize}', '#{escape_javascript(fields)}')"), :id => "#{item_id}_add_comment")
  end

end

app/views/projects/_burndown_trend_section.html.erb
<div class="content_section">
  <h2>Sprint Burndown
    <div class="right_link">
      <%= all_sprints = @sprints_select << @sprint
          select_tag "sprint",
                     options_for_select(all_sprints.reverse.map { |i| i == @sprint ? ["Current", i] : ["Sprint #{i}", i] }, @sprint),
                     :id => @project.id, :class => "burndown_sprint_select" %>
    </div>
  </h2>
  <div id="burndown_chart"></div>
  <script type="text/javascript" charset="utf-8">
      draw_burndown_chart(<%= @burndown_chart_point_start %>, <%= @burndown_chart_point_interval %>,
              <%= @actual_burndown_chart_data_series %>, <%= @idle_burndown_chart_data_series %>);
  </script>
</div>

app/views/projects/_control_panel.html.erb
<div class="controlPanel tabs" id="controlPanel">
  <div class="row" id="project_name_row">
    <div class="projectName" id="project_tabs">
      <ul>
        <% current_user.projects.each do |project| %>
            <% if project.eql?(@project) %>
                <li class="current">
                  <span><%= truncate(project.name, :length => 20) %></span>
                </li>
            <% else %>
                <li originalwidth="132">
                  <%= link_to truncate(project.name, :length => 20), project_path(project) %>
                  <span></span>
                </li>
            <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row" id="controls_search_velocity_row">
    <div class="right clearfix">
      <% if view.eql? "project" %>
          <%= link_to 'Import CSV', import_pivotal_csv_project_path(@project) %>
          <a href="#" id="add_new_story_control_button">Add Story +</a>
      <% end %>

      <span class="ieInputWrapper">
        <%= form_tag search_project_path(@project), :remote => true do %>
            <input type="text" size="20" id="search_term" name="search_term" value="" class="searchField">
        <% end %>
      </span>

      <div id="velocity">
        <table id="projectStatus" class="projectStatusTable">
          <tbody>
          <tr>
            <td class="velocityLabel">velocity</td>
            <td>
              <div class="projectVelocity" id="velocity_projectVelocity"><%= @project.velocity %></div>
            </td>
          </tr>
          </tbody>
        </table>
      </div>

    </div>

    <% if view.eql? "project" %>
        <ul class="clearfix" id="buttonPanel">
          <div style="margin-right: 216px; float:right">
            <%= image_tag "ajax-loader.gif", :alt => "Spinner", :class => "ajax-loader" %>
          </div>

          <ul class="clearfix" id="panelList">
            <% Story.categories.each do |category| %>
                <% button_class = 'selected' %>
                <% if category != 'icebox' %>
                    <% button_class = @project.stories.where(:category => category).present? ? 'selected' : '' %>
                <% end %>
                <li>
                  <a id="<%= "#{category}_control_button" %>" href="#" class="<%= "control_button button #{button_class}" %>"><%= category.capitalize %></a>
                </li>
            <% end %>

          </ul>
          <li>
            <%= link_to "Sprint View", sprint_project_path, :class => "button", :id => "show_sprint_button" %>
          </li>
        </ul>
    <% elsif view.eql? "sprint" %>
        <ul class="clearfix" id="buttonPanel">
          <div style="margin-right: 216px; float:right">
            <%= image_tag "ajax-loader.gif", :alt => "Spinner", :class => "ajax-loader" %>
          </div>

          <ul class="clearfix" id="panelList">
            <% sprint_work = @project.stories.select { |wi| wi.category.eql? "current" } %>
            <li>
              <a id="dev_ready_control_button" href="#"
                 class="<%= "control_button button #{sprint_work.select { |wi| wi.not_yet_started? }.present? ? "selected" : ""}" %>">
                Dev Ready
              </a>
            </li>
            <li>
              <a id="in_progress_control_button" href="#"
                 class="<%= "control_button button #{sprint_work.select { |wi| wi.started? }.present? ? "selected" : ""}" %>">
                In Progress
              </a>
            </li>
            <li>
              <a id="dev_done_control_button" href="#"
                 class="<%= "control_button button #{sprint_work.select { |wi| wi.finished? }.present? ? "selected" : ""}" %>">
                Dev Done
              </a>
            </li>
            <li>
              <a id="qa_ready_control_button" href="#"
                 class="<%= "control_button button #{sprint_work.select { |wi| wi.delivered? }.present? ? "selected" : ""}" %>">
                QA Ready
              </a>
            </li>
            <li>
              <a id="qa_done_control_button" href="#"
                 class="<%= "control_button button #{sprint_work.select { |wi| wi.accepted? or wi.rejected? }.present? ? "selected" : ""}" %>">
                QA Done
              </a>
            </li>
            <li>
              <a id="burndown_control_button" href="#" class="<%= "button" %>">Burndown</a>
            </li>
          </ul>
          <li>
            <%= link_to "Project View", project_path, :class => "button", :id => "show_project_button" %>
          </li>
        </ul>
    <% end %>
  </div>
</div>

app/views/projects/_form.html.erb
<div class="action_area">
  <%= form_for(@project) do |f| %>
      <% if @project.errors.any? %>
          <div class="error_message">
            <h3><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>

            <ul>
              <% @project.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <table class="form_table">
        <tbody>
        <tr>
          <td class="label_column">
            <%= f.label :name %>
          </td>
          <td class="field_column">
            <%= f.text_field :name, :size => 87 %>
          </td>
        </tr>
        <tr>
          <td class="label_column" valign="top">
            <%= f.label :description %>
          </td>
          <td class="field_column">
            <%= f.text_area :description, :rows => 10, :cols=> 25 %>
            <br>
          </td>
        </tr>
        <tr>
          <td class="label_column">
            <%= f.label :estimate_bugs %>
          </td>
          <td class="field_column">
            <%= f.check_box :estimate_bugs %>
            <br>
          </td>
        </tr>
        <tr>
          <td class="label_column">
            <%= f.label :estimate_chores %>
          </td>
          <td class="field_column">
            <%= f.check_box :estimate_chores %>
            <br>
          </td>
        </tr>
        <tr>
          <td class="label_column">
            <%= f.label :sprint_length %>
          </td>
          <td class="field_column">
            <%= f.select :sprint_length, [1, 2, 3, 4] %> <span class="text_example">(in weeks)</span>
            <br>
          </td>
        </tr>
        <tr>
          <td class="label_column">
            <%= f.label :start_date %>
          </td>
          <td class="field_column">
            <%= f.date_select :start_date, :start_year => DateTime.now.year - 5 , :order => [:day, :month, :year] %>
            <br>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>
            <%= f.submit %>
          </td>
        </tr>
        </tbody>
      </table>
  <% end %>
</div>

app/views/projects/_project_box_details.html.erb
<div class="project_title"><%= truncate(project.name.capitalize, :length => 45) %></div>
<div class="project_box_hover_links">
  <% if current_user.belongs_to_project?(project) %>

      <%= link_to 'Stories', project, :class => "hover_link" %>
      <%= link_to 'Members', project_project_users_path(project),:class => "hover_link" %>
      <%= link_to 'Overview', overview_project_path(project), :class => "hover_link" %>
  <% else %>
      <%= link_to 'Join', join_project_path(project), :remote=> true %>
  <% end %>
</div>
<div class="velocity" title="Velocity: 4"><%= project.velocity %></div>

app/views/projects/_project_page_main_menu.html.erb
<h1><%= truncate(project.name.capitalize, :length => 40) %> : <%= sub_page %>
  <div class="right_link">
    <%= collection_select(:project, :id, current_user.projects, :id,
                          :truncated_name,
                          {:prompt => true},
                          {:id => project.id, :class => "project_select"}) %>
    <%= link_to "View Stories", project_path(project), :id => "view_stories" %>
  </div>
</h1>
<div class="subnav clearfix">
  <ul class="buttons">
    <li>
      <%= link_to 'Overview', overview_project_path(project),
                  :class => "button #{sub_page.eql?("Overview") ? "current" : ""}" %>
    </li>
    <li>
      <%= link_to 'Members', project_project_users_path(project),
                  :class => "button #{sub_page.eql?("Members") ? "current" : ""}" %>
    </li>
    <li>
      <%= link_to 'Reports', reports_project_path(project),
                  :class => "button #{sub_page.eql?("Reports") ? "current" : ""}" %>
    </li>
    <li>
      <a class="button" title="Coming Soon" href="#">Export</a>
    </li>
    <li>
      <%= link_to 'Import', import_pivotal_csv_project_path(project),
                  :class => "button #{sub_page.eql?("Import") ? "current" : ""}" %>
    </li>
    <li class="last">
      <%= link_to "Project Profile", edit_project_path(@project), :class => "button #{sub_page.eql?("Project Profile") ? "current" : ""}" %>
    </li>
  </ul>
</div>

app/views/projects/_sprint_state_panel.html.erb
<td id="<%= state %>" class="<%= "#{state} panel" %>" width="20%" style="<%= stories_in_state.present? ? "" : "display:none"%>">
  <div class="panelHeaderRight"></div>
  <div class="panelHeaderLeft"></div>
  <div class="panelHeader">
    <div id=<%= "#{state}_title" %>>
      <a href="#" class="closePanel panelLink" id='<%= "#{state}_close" %>' title="Close panel"></a>
      <span class="panelTitle"><%= state.gsub('_',' ').humanize %> </span>
      <span class="external_icon"></span>
    </div>
  </div>
  <div id="<%= "#{state}_item_list" %>" class="list">
    <div class="btm">
      <div class="right"></div>
      <div class="left"></div>
      <div class="mid"></div>
    </div>
    <div id="<%= "#{state}_items" %>" class="items">
      <div id="<%= "#{state}_scrolling_item_list" %>" class="inner scrolling_item_list">
        <% if stories_in_state.present? %>
            <% stories_in_state.each do |story| %>
                <%= render :partial => 'stories/story', :locals => {:story => story} %>
            <% end %>
        <% else %>
            <div id="no_stories" class="no_stories">
              Nothing yet.
            </div>
        <% end %>
        <div id="<%= "#{state}_item_list_end" %>" class="endOfList"></div>
      </div>
    </div>
  </div>
</td>

app/views/projects/_story_trend_section.html.erb
<div class="content_section">
  <h2>Story Trend
    <div class="right_link">
      <%= form_tag update_story_trend_report_project_path, :remote => true do %>
          <%= select_tag "from_sprint", options_for_select(@sprints_select.reverse.map{|i|["Sprint #{i}", i]}, @from_sprint) %>
          To : <%= select_tag "to_sprint", options_for_select(@sprints_select.reverse.map{|i|["Sprint #{i}", i]}, @to_sprint) %>
          <%= submit_tag "Show Trend" %>
      <% end %>
    </div>
  </h2>
  <div id="points_break_down_chart"></div>
  <script type="text/javascript" charset="utf-8">
      draw_story_trend_chart(<%= @sprints_from_to %>, <%= @chores_trend %>, <%= @bugs_trend %>, <%= @features_trend %>);
  </script>
</div>

app/views/projects/create.js.erb
$('#no_project_message').hide();
$('#project_list').prepend('<%=escape_javascript render :partial => 'project_box', :locals => {:project => @project} %>');
ajax_flash_notice('New Project created successfully!!');
highlight_item($('#<%=@project.id%>_project_box'));

app/views/projects/edit.html.erb
<% title "Project Overview" %>
<div class="project_pages">
  <%= render :partial => 'projects/project_page_main_menu', :locals => {:project => @project, :sub_page => "Project Profile"} %>

  <h2>Project Profile</h2>
  <%= render 'form' %>
</div>

app/views/projects/import_pivotal_csv.html.erb
<% title "Project Import" %>
<div class="project_pages">
  <%= render :partial => 'projects/project_page_main_menu', :locals => {:project => @project, :sub_page => "Import"} %>

  <h2>Import CSV</h2>

  <div class="action_area" id="add_member">
    <table class="action_cells">
      <tbody>
      <tr>
        <%= form_tag upload_pivotal_csv_project_path, :multipart => true do %>
            <td><label>Select a CSV</label></td>
            <td><%= file_field_tag "file" %>
            </td>
            <td>
              <%= submit_tag("Import") %>
            </td>
        <% end %>
      </tr>
      <tr>
        <td></td>
        <td class="text_example" colspan="3">Only for Pivotal Tracker as of Now!!</td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/join.js.erb
$('#<%= @project.id %>_project_box').html('<%=escape_javascript render :partial => 'projects/project_box_details', :locals => {:project => @project} %>');
ajax_flash_notice('You joined the project successfully!!');
highlight_item($('#<%=@project.id%>_project_box'));

app/views/projects/search.js.erb
<% if @error.present? %>
    ajax_flash_notice("<%="#{@error}"%>");
<% else %>
    $('#panels').append('<%=escape_javascript render :partial => 'stories/stories_panel', :locals => {:stories => @search_results, :category => "search", :search_term => @search_term } %>');
    <% if @search_results.present? %>
        <% @search_results.each do |story| %>
        attachTokenInput($('#<%= story.id %>_labels'));
        <% end %>
    <% end %>
<% end %>

app/views/projects/show.html.erb
<% title @project.name.camelcase %>
<%= render :partial => 'projects/control_panel', :locals => {:view => "project"} %>
<div id="all_panels" class="story_content">
  <table id="layout" class="layout" cellspacing="16px">
    <tbody>
    <tr id="panels">
      <% Story.categories.each do |category| %>
          <% stories = @project.stories.includes([ :comments, :tasks, :labels, :story_attachments ]).where(:category => category).limit(30) %>
          <%= render :partial => 'stories/stories_panel', :locals => {:stories => stories, :category => category}  %>
      <% end %>
    </tr>
    </tbody>
  </table>
</div>

<script type="text/javascript">
    estimate_bugs = <%= @project.estimate_bugs? %>;
    estimate_chores = <%= @project.estimate_chores? %>;
    view = "project";
</script>

app/views/projects/update_velocity_trend_report.js.erb
draw_velocity_trend_chart(<%= @velocity_trend %>,<%= @from_sprint %>);