config/routes.rb
Agiledme::Application.routes.draw do

  resources :epics do
    member do
      get :finish
    end
  end

  resources :labels

  resources :projects do
    member do
      get :join, :leave, :overview, :reports, :sprint, :import_pivotal_csv, :show_more_items
      post :upload_pivotal_csv, :search, :update_velocity_trend_report, :update_story_trend_report, :update_burndown_chart
    end
    resources :project_users
    resources :stories do
      member do
        get :start, :finish, :deliver, :accept, :reject, :restart, :estimate, :un_start, :un_finish, :un_deliver
        put :update_category_and_priority
      end
      resources :story_histories

    end
    resources :epics, :controller => :stories
    resources :features, :controller => :stories
    resources :bugs, :controller => :stories
    resources :chores, :controller => :stories
  end

  resources :story_attachments do
    member do
      get :download_attachment
    end
  end

  devise_for :users, :controllers => {:registrations => 'users/registrations'}

  root :to => "dashboard#index"

end

app/models/story.rb
class Story < ActiveRecord::Base

  MINIMUM_POSSIBLE_PRIORITY = 0
  UN_ESTIMATED_VALUE = -1
  include AASM

  belongs_to :project
  belongs_to :epic, :class_name => 'Story'

  has_many :story_histories, :dependent => :destroy
  has_many :tasks, :order=>"updated_at DESC", :dependent => :destroy
  has_many :comments, :order=>"updated_at DESC", :dependent => :destroy
  has_many :story_attachments, :order=>"updated_at DESC", :dependent => :destroy
  has_many :story_labels, :dependent => :destroy
  has_many :labels, :through => :story_labels

  accepts_nested_attributes_for :tasks, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :comments, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :story_attachments, :allow_destroy => true, :reject_if => :all_blank

  attr_reader :label_tokens

  def label_tokens=(ids)
    ids.gsub!(/CREATE_(.+?)_END/) do
      Label.create!(:name => $1).id
    end
    self.label_ids = ids.split(",")
  end

  validates_presence_of :title
  validates_presence_of :category

  after_create :set_initial_default_values

  aasm_initial_state :not_yet_started

  aasm :column => :status do
    state :not_yet_started
    state :started, :enter => :update_started_by
    state :finished, :enter => :update_finished_by
    state :delivered, :enter => :update_delivered_by
    state :accepted, :enter => :update_accepted_by
    state :rejected, :enter => :update_rejected_by

    event :start do
      transitions :to => :started, :from => [:not_yet_started]
    end

    event :un_start do
      transitions :to => :not_yet_started, :from => [:started]
    end

    event :finish do
      transitions :to => :finished, :from => [:started]
    end

    event :un_finish do
      transitions :to => :started, :from => [:finished]
    end

    event :deliver do
      transitions :to => :delivered, :from => [:finished]
    end

    event :un_deliver do
      transitions :to => :finished, :from => [:delivered]
    end

    event :accept do
      transitions :to => :accepted, :from => [:delivered]
    end

    event :reject do
      transitions :to => :rejected, :from => [:delivered]
    end

    event :restart do
      transitions :to => :started, :from => [:rejected]
    end
  end

  def self.next_priority_for(category)
    max_priority = Story.maximum('priority', :group => 'category')[category]
    max_priority.present? ? max_priority + 1 : 0
  end

  def self.types
    %w[Feature Bug Chore Epic]
  end

  def self.fibonacci_estimates
    %w[0 1 2 3 5 8]
  end

  def self.categories
    %w[done current backlog icebox]
  end

  def self.estimates
    {"Unestimated" => UN_ESTIMATED_VALUE, "0 Points" => 0, "1 Points" => 1, "2 Points" => 2, "3 Points" => 3, "5 Points" => 5, "8 Points" => 8}
  end

  def is_ready?
    !is_estimatable? or (is_estimatable? and is_estimated?)
  end

  def is_estimated?
    self.estimate.present? and self.estimate != UN_ESTIMATED_VALUE
  end

  def is_unestimated?
    is_estimatable? and !is_estimated?
  end

  def is_estimatable?
    raise "wrong call : #{self.inspect}"
  end

  def add_history(event)
    StoryHistory.new(:event => event,
                     :user_id => User.current_user.id,
                     :story_id => self.id,
                     :project_id => self.project.id).save!
  end

  def prioritize_above(other_item_id)
    other_item = Story.find(other_item_id)
    other_priority = other_item.priority
    other_category = other_item.category
    if re_prioritized_in_same_category?(other_category)
      if has_priority_increased?(other_priority)
        decrement_priorities_of_all_items_between_this_and_other_item(other_priority)
      elsif has_priority_decreased?(other_priority)
        increment_priorities_of_all_items_between_this_and_other_item(other_priority)
      end
      self.update_attributes!(:priority => other_priority)
    else
      other_item.increment_priorities_of_all_items_of_higher_priority
      self.update_attributes!(:priority => (other_priority + 1), :category => other_category)
    end
  end

  def update_status_change_history
    if changed_attributes["status"].present?
      if self.not_yet_started?
        add_history("un started this "+ self.type.downcase)
      elsif self.started?
        update_started_by
      elsif self.finished?
        update_finished_by
      elsif self.delivered?
        update_delivered_by
      elsif self.accepted?
        update_accepted_by
      elsif self.rejected?
        update_rejected_by
      else
        add_history(self.status " this "+ self.type.downcase)
      end
    end
  end

  def increment_priorities_of_all_items_of_higher_priority
    all_items_of_higher_priority = self.project.stories.where("priority > ? and category = ?", self.priority, self.category)
    all_items_of_higher_priority.each do |item|
      item.update_attributes!(:priority => (item.priority + 1))
    end
  end

  private

  def re_prioritized_in_same_category?(category)
    self.category.eql? category
  end

  def has_priority_increased?(other_priority)
    self.priority < other_priority
  end

  def has_priority_decreased?(other_priority)
    self.priority > other_priority
  end

  def decrement_priorities_of_all_items_between_this_and_other_item(other_priority)
    items_between_this_and_other = self.project.stories.where("priority > ? AND priority <= ? and category = ?", self.priority, other_priority, self.category)
    items_between_this_and_other.each do |item|
      item.update_attributes!(:priority => (item.priority - 1))
    end
  end

  def increment_priorities_of_all_items_between_this_and_other_item(other_priority)
    items_between_this_and_other = self.project.stories.where("priority < ? AND priority >= ? and category = ?", self.priority, other_priority, self.category)
    items_between_this_and_other.each do |item|
      item.update_attributes!(:priority => (item.priority + 1))
    end
  end

  def increment_priorities_of_all_items_in_current
    Story.where(:category => 'current').each do |item|
      item.update_attributes!(:priority => (item.priority + 1))
    end
  end

  def set_initial_default_values
    if self.category.blank?
      self.category = 'icebox'
      self.priority = Story.next_priority_for("icebox")
      self.save
      add_history("created this "+ self.type.downcase)
    else
      add_history("imported this "+ self.type.downcase)
    end
  end

  def update_started_by
    add_history("started this "+ self.type.downcase)
    self.started_at = Time.now
    set_owner_as_current_user
    move_item_to_current_category unless self.category.eql? "current"
  end

  def move_item_to_current_category
    self.category = "current"
    priority_to_set = Story.where(:category => 'current').minimum(:priority)
    if priority_to_set.present?
      increment_priorities_of_all_items_in_current
      self.priority = priority_to_set
    else
      self.priority = MINIMUM_POSSIBLE_PRIORITY
    end
  end

  def update_finished_by
    add_history("finished this "+ self.type.downcase)
    self.finished_at = Time.now
    set_owner_as_current_user
  end

  def update_delivered_by
    add_history("delivered this "+ self.type.downcase)
    self.delivered_at = Time.now
    set_owner_as_current_user
  end

  def update_accepted_by
    add_history("accepted this "+ self.type.downcase)
    self.accepted_at = Time.now
    self.save!
  end

  def update_rejected_by
    add_history("rejected this "+ self.type.downcase)
    self.rejected_at = Time.now
    self.save!
  end

  def update_restarted_by
    add_history("restarted this "+ self.type.downcase)
    set_owner_as_current_user
  end

  def set_owner_as_current_user
    self.owner = User.current_user.id
    self.save!
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  before_filter :find_story_and_set_project, :except => :create

  # POST /stories
  # POST /stories.xml
  def create
    @project = current_user.projects.find(params[:project_id])
    @story = get_story_object(params[:story][:type])
    @story.project = @project

    @story.story_attachments = StoryAttachment.where(:user_id => current_user.id, :story_id => nil)
    respond_to do |format|
      if @story.save
        format.js
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' was successfully created.') }
        format.xml { render :xml => @story, :status => :created, :location => @story }
      else
        format.js { render :template => 'stories/error' }
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  def get_story_object(type)
    if type == "Feature"
      Feature.new(params[:story])
    elsif type == "Bug"
      Bug.new(params[:story])
    elsif type == "Chore"
      Chore.new(params[:story])
    elsif type == "Epic"
      Epic.new(params[:story])
    end
  end

  # PUT /stories/1
  # PUT /stories/1.xml
  def update
    @pre_category = @story.category
    params_req = params[:story] || params[@story.type.downcase]
    @story.type = params_req[:type] || params_req[:type]

    respond_to do |format|
      if @story.update_attributes(params_req)
        @story.update_status_change_history
        @message = "#{@story.type} was updated"
        @story.story_attachments.reload
        format.js { render :template => 'stories/action_success' }
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' was successfully updated.') }
        format.xml { head :ok }
      else
        format.js { render :template => 'stories/error' }
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update_category_and_priority

    respond_to do |format|
      if @story.prioritize_above(params[:item_dropped_on_id].to_i)
        format.js { render :js => "ajax_flash_notice('Updated successfully!!');" }
      else
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  def start
    @pre_category = @story.category

    respond_to do |format|
      if @story.start!
        format.js { render :template => 'stories/action_success' }
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' was successfully started.') }
        format.xml { head :ok }
      else
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  def un_start
    respond_to do |format|
      if @story.un_start!
        @message = "Rolled back #{@story.type} start."
        format.js { render :template => 'stories/action_success' }
        format.html { redirect_to(project_url(@story.project), :notice => 'Rolled back '+@story.type + ' start.') }
        format.xml { head :ok }
      else
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  def estimate
    @message = "#{@story.type} was estimated as #{params[:estimate]}"

    respond_to do |format|
      if @story.update_attributes(:estimate => params[:estimate])
        @message = "#{@story.type} was estimated as #{params[:estimate]} pointer"
        format.js { render :template => 'stories/action_success' }
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' was successfully estimated as a ' + params[:estimate] +" pointer.") }
        format.xml { head :ok }
      else
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  def finish
    respond_to do |format|
      if @story.finish!
        format.js { render :template => 'stories/action_success' }
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' was successfully finished.') }
        format.xml { head :ok }
      else
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  def un_finish
    respond_to do |format|
      if @story.un_finish!
        @message = "Rolled back #{@story.type} finish."
        format.js { render :template => 'stories/action_success' }
        format.html { redirect_to(project_url(@story.project), :notice => 'Rolled back '+@story.type + ' finish.') }
        format.xml { head :ok }
      else
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  def deliver
    respond_to do |format|
      if @story.deliver!
        format.js { render :template => 'stories/action_success' }
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' was successfully delivered.') }
        format.xml { head :ok }
      else
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  def un_deliver
    respond_to do |format|
      if @story.un_deliver!
        @message = "Rolled back #{@story.type} deliver."
        format.js { render :template => 'stories/action_success' }
        format.html { redirect_to(project_url(@story.project), :notice => 'Rolled back '+@story.type + ' delivery.') }
        format.xml { head :ok }
      else
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  def accept
    respond_to do |format|
      if @story.accept!
        format.js { render :template => 'stories/action_success' }
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' was successfully accepted.') }
        format.xml { head :ok }
      else
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  def reject
    respond_to do |format|
      if @story.reject!
        format.js { render :template => 'stories/action_success' }
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' was rejected.') }
        format.xml { head :ok }
      else
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  def restart
    respond_to do |format|
      if @story.restart!
        format.js { render :template => 'stories/action_success' }
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' was successfully restarted.') }
        format.xml { head :ok }
      else
        format.html { redirect_to(project_url(@story.project), :notice => @story.type + ' ERROR.') }
        format.xml { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.xml
  def destroy
    @story.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to(project_url(@project), :notice => @story.type + ' was successfully deleted.') }
      format.xml { head :ok }
    end
  end

  private

  def find_story_and_set_project
    @story = Story.find(params[:id])
    @project = @story.project
  end

  def prepare_attachments
    attachments = []
    params[:story][:story_attachments_attributes].each do |index, image|
      image[:image].each do |file|
        attachments << {:image => file, :user_id => current_user.id}
      end
    end
    params[:story][:story_attachments_attributes] = attachments
  end

end

app/views/stories/_new_story.html.erb
<%
   story = Story.new
   story.story_attachments.build
   story.project = project
   story.requester = current_user.id
   if epic_id.present?
       story.epic_id = epic_id
   end

%>
<%= render :partial => 'stories/story_detail', :locals => {:story => story} %>

app/views/stories/_story_actions.html.erb
<% item_unique_id = "#{story.id}" %>
<% if story.is_a?(Epic) %>
    <a href="#" id="<%= story.id %>_epic" class="stateChangeButton notDblclickable start add_new_epic_story">Add Story +</a>
<% else %>
    <% if story.is_unestimated? %>
        <% Story.fibonacci_estimates.each do |estimate| %>
            <%= link_to image_tag("estimate#{estimate}pt.gif",
                                  :class => "estimateButton notDblclickable",
                                  :title => "Estimate: #{estimate} point"),
                        estimate_project_story_path(story.project, story, {:estimate => estimate}),
                        :id => "#{item_unique_id}_estimate#{estimate}Button",
                        :remote => true %>
        <% end %>
    <% elsif story.not_yet_started? and story.is_ready? %>
        <%= link_to "Start", start_project_story_path(story.project, story),
                    :id => "#{item_unique_id}_start_button",
                    :class => "stateChangeButton notDblclickable start",
                    :remote => true %>
    <% elsif story.started? %>
        <%= link_to "Finish", finish_project_story_path(story.project, story),
                    :id => "#{item_unique_id}_finish_button",
                    :class => "stateChangeButton notDblclickable finish",
                    :remote => true %>
        <%= link_to "Un-Start", un_start_project_story_path(story.project, story),
                    :id => "#{item_unique_id}_finish_button",
                    :class => "stateChangeButton notDblclickable unstart",
                    :remote => true %>
    <% elsif story.finished? %>
        <%= link_to "Deliver", deliver_project_story_path(story.project, story),
                    :id => "#{item_unique_id}_deliver_button",
                    :class => "stateChangeButton notDblclickable deliver",
                    :remote => true %>
        <%= link_to "Un-Finish", un_finish_project_story_path(story.project, story),
                    :id => "#{item_unique_id}_deliver_button",
                    :class => "stateChangeButton notDblclickable unfinish",
                    :remote => true %>
    <% elsif story.delivered? %>
        <%= link_to "Accept", accept_project_story_path(story.project, story),
                    :id => "#{item_unique_id}_accept_button",
                    :class => "stateChangeButton notDblclickable accept",
                    :remote => true %>
        <%= link_to "Reject", reject_project_story_path(story.project, story),
                    :id => "#{item_unique_id}_reject_button",
                    :class => "stateChangeButton notDblclickable reject",
                    :remote => true %>
        <%= link_to "Un-Deliver", un_deliver_project_story_path(story.project, story),
                    :id => "#{item_unique_id}_reject_button",
                    :class => "stateChangeButton notDblclickable undeliver",
                    :remote => true %>
    <% elsif story.rejected? %>
        <%= link_to "Restart", restart_project_story_path(story.project, story),
                    :id => "#{item_unique_id}_restart_button",
                    :class => "stateChangeButton notDblclickable restart",
                    :remote => true %>
    <% end %>
<% end %>

app/views/stories/_story_detail.html.erb
<% if story.new_record?
       item_unique_id = story.epic.present? ? "#{story.epic.id}_epic_new_story" : "icebox_new_story"
       item_type_image_source = "feature.png"
       item_estimate_image_source = "estimate-1pt.gif"
   else
       item_unique_id = "#{story.id}"
       item_type_image_source = "#{story.type.downcase}.png"
       item_estimate_image_source = "estimate#{story.estimate}pt.gif"
   end
%>

<div id="<%= "#{item_unique_id}_detail" %>" class="item" style="display:none">
<div id="<%= "#{item_unique_id}_content" %>" class="storyItem unscheduled unestimated underEdit jquery_file_upload">
<%= form_for([story.project, story], :remote => true, :html => {:multipart => true}) do |wi| %>
    <% @project_users ||= story.project.active_users %>

    <div class="storyPreviewHeader">
      <% if !story.new_record? %>
          <div class="storySelector notDblclickable">&nbsp;</div>
          <div class="icons">
            <%= image_tag "story_expanded.png",
                          :id => "#{item_unique_id}_cancel_edit_button",
                          :alt => "Collapse",
                          :title => "Collapse",
                          :class => "toggleExpandedButton cancelEditButton" %>
          </div>
      <% end %>
      <div class="storyPreviewInput">
        <%= wi.text_area :title,
                         :cols => 1,
                         :rows => 1,
                         :id =>"#{item_unique_id}_title",
                         :class => 'titleInputField autoresize' %>
        <div class="clear">
        </div>
      </div>
      <div class="text_example">e.g. As a role, I want goal so that benefit</div>
      <div class="error_message" id="<%= "#{item_unique_id}_story_error_message" %>" style="display:none;"></div>
    </div>
    <div class="storyDetailElement">
    <div class="storyDetails">
    <div class="buttons">
      <div class="storyDetailsButton">
        <%= wi.submit 'Save', :class => "story_save", :id => "#{item_unique_id}_save_button" %>
        <input id="<%= "#{item_unique_id}_cancel_edit_button" %>" class="cancelEditButton" type="button" value="Cancel">
        <% if !story.new_record? %>
            <%= link_to 'Delete', project_story_path(@project, story), :confirm => "Are you sure you want to delete the #{story.type}?", :method => :delete, :remote => true %>
        <% else %>
            <input type="submit" value="Delete" disabled="disabled">
            <input type="submit" value="View history" disabled="disabled">
        <% end %>
      </div>
      <% if !story.new_record? %>
          <div id="<%= item_unique_id %>_content_buttons" style="margin-left:-4px;margin-top:5px">
            <%= render :partial => 'stories/story_actions', :locals => {:story => story} %>
          </div>
      <% end %>
    </div>
    <table class="storyDetailsTable">
      <tbody>
      <tr>
        <td colspan="1" class="letContentExpand">
          <div>
            <%= wi.select(:type, Story.types,
                          {:selected => story.new_record? ? 'Feature' : story.type},
                          {:class => "storyDetailsField story_type_select",
                           :id => "#{item_unique_id}_type"}) %>
          </div>
        </td>
        <td colspan="1" class="storyDetailsLabelIcon">
          <%= image_tag item_type_image_source, :id => "#{item_unique_id}_type_image" %>
        </td>
        <td colspan="1" class="lastCell">
          <div id="<%= "#{item_unique_id}_help_story_types" %>">
            <%= image_tag("question_mark.gif", :alt => "Story type help", :class => "helpIcon") %>
            <%= render :partial => 'stories/story_type_tooltip', :locals => {:id => item_unique_id} %>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="1">
          <div>
            <%= wi.select(:estimate, Story.estimates,
                          {:selected => story.new_record? ? -1 : story.estimate},
                          {:class => "storyDetailsField story_estimate_select",
                           :id => "#{item_unique_id}_estimate",
                           :disabled => (!story.new_record? and !story.is_estimatable?)}) %>
          </div>
        </td>
        <td colspan="1" class="storyDetailsLabelIcon">
          <% if story.new_record? or story.is_estimatable? %>
              <%= image_tag item_estimate_image_source, :id => "#{item_unique_id}_estimate_image" %>
          <% end %>
        </td>
        <td colspan="1">
          <div id="<%= "#{item_unique_id}_help_estimates" %>">
            <%= image_tag("question_mark.gif", :alt => "Story estimation help", :class => "helpIcon") %>
            <%= render :partial => 'stories/story_estimate_tooltip', :locals => {:id => item_unique_id} %>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div>
            <%= wi.collection_select(:requester, @project_users, :id, :display_name, {}, {:class => "storyDetailsField"}) %>
          </div>
        </td>
        <td colspan="3">
          <label id="story_requester_label" for="story_requester">
            <div>
              <div class="emphasizedFieldLabel">requested</div>
              <div class="fieldLabel">this story</div>
            </div>
          </label>
        </td>
      </tr>
      <tr>
        <td colspan="1">
          <div>
            <%= wi.collection_select(:owner, @project_users, :id, :display_name, {:prompt => "none"}, {:class => "storyDetailsField"}) %>
          </div>
        </td>
        <td colspan="3">
          <label>
            <div>
              <div class="emphasizedFieldLabel">owns</div>
              <div class="fieldLabel">this story</div>
            </div>
          </label>
        </td>
      </tr>
      <% if story.epic_id.present? %>
          <tr>
            <td colspan="4">
              <div>
                <%= "Epic is : #{story.epic.title}" %>
              </div>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <div class="section">
      <div class="header">
        <div class="label">Labels</div>
      </div>
      <div class="wrapper token_wrapper">
        <%= wi.text_field :label_tokens,
                          :class => "labels",
                          :id => "#{item_unique_id}_labels",
                          "data-pre" => story.labels.all.to_json,
                          "data-url" => "/labels.json?project_id=#{story.project.id}" %>
      </div>
    </div>
    <div class="section">
      <div class="storyDescriptionTable">
        <div class="header">
          <div class="label">Description</div>
          <div id="<%= "#{item_unique_id}_help_story_description" %>">
            <%= image_tag("question_mark.gif", :alt => "Story description help", :class => "helpIcon") %>
            <%= render :partial => 'stories/story_description_tooltip', :locals => {:id => item_unique_id} %>
          </div>
          <div class="clear">
          </div>
        </div>
        <div>
          <%= wi.text_area :description,
                           :cols => 1,
                           :rows => 1,
                           :id => "#{item_unique_id}_description",
                           :class => 'textAreaFocus description_area autoresize' %>
        </div>
      </div>
    </div>
    <div class="taskTableDiv">
      <div class="section">
        <div id="<%= "#{item_unique_id}_tasks_header" %>" class="header">
          Tasks <span class="count">(<%= story.tasks.count %>)</span>
        </div>
        <ol id="<%= "#{item_unique_id}_tasks" %>" class="task_list ui-sortable">
          <%= wi.fields_for :tasks do |task_builder| %>
              <%= render :partial => 'stories/task_fields', :locals => {:f => task_builder} %>
          <% end %>
        </ol>
        <div class="add_task">
          <textarea id="<%= "#{item_unique_id}_new_task_description" %>"
                    cols="1" rows="1"
                    class="tasksTextArea autoresize new_task_text">add new task</textarea>
              <span id="<%= "#{item_unique_id}_new_task_add_link" %>" class="add_task" style="display:none;">
                <%= link_to_add_task_fields "Add", wi, :tasks, item_unique_id %>
              </span>
        </div>
      </div>
    </div>
    <div class="commentTableDiv">
      <div class="section">
        <div id="<%= "#{item_unique_id}_comments_header" %>" class="header">
          Comments <span class="commentCount">(<%= story.comments.count %>)</span>
        </div>
        <table class="commentsTable">
          <tbody id="<%= "#{item_unique_id}_comments" %>">
          <%= wi.fields_for :comments do |comment_builder| %>
              <%= render :partial => 'stories/comment_fields', :locals => {:f => comment_builder} %>
          <% end %>
          </tbody>
        </table>
        <div class="add_comment">
          <textarea id="<%= "#{item_unique_id}_new_comment_description" %>"
                    cols="20" rows="1"
                    class="tasksTextArea autoresize new_comment_text">add new comment</textarea>

          <div class="commentText">(Format using *<b>bold</b>* and _<i>italic</i>_ text.)</div>
              <span id="<%= "#{item_unique_id}_new_comment_add_link" %>" class="add_comment" style="display:none;">
                <%= link_to_add_comment_fields "Add", wi, :comments, item_unique_id %>
              </span>
        </div>
      </div>
    </div>
    <%= wi.hidden_field :category %>
    <%= wi.hidden_field :priority %>
    <%= wi.hidden_field :epic_id %>
    <%= wi.hidden_field :project_id, {:value => story.project.id} %>
    <div class="attachmentWidget">
      <div class="section attachments">
        <div id="<%= "#{item_unique_id}_attachments_header" %>" class="header">
          Attachments <span class="count">(<%= story.story_attachments.count %>)</span>
        </div>
        <ol id="<%= "#{item_unique_id}_attachments_list" %>" class="attachments_list">
          <%= wi.fields_for :story_attachments do |story_attachment_builder| %>
              <% if !story_attachment_builder.object.new_record? %>
                  <%= render :partial => 'stories/attachment_fields', :locals => {:f => story_attachment_builder} %>
              <% end %>
          <% end %>
        </ol>
      </div>
    </div>
<% end %>
<%= render :partial => 'story_attachments/form', :locals => {:story => story} %>
</div>
</div>
</div>
</div>

app/views/stories/destroy.js.erb
$('#<%= @story.id %>_item_box').remove();
ajax_flash_notice('<%="#{@story.type} was deleted."%>');