config/routes.rb
Agiledme::Application.routes.draw do

  resources :epics do
    member do
      get :finish
    end
  end

  resources :labels

  resources :projects do
    member do
      get :join, :leave, :overview, :reports, :sprint, :import_pivotal_csv, :show_more_items
      post :upload_pivotal_csv, :search, :update_velocity_trend_report, :update_story_trend_report, :update_burndown_chart
    end
    resources :project_users
    resources :stories do
      member do
        get :start, :finish, :deliver, :accept, :reject, :restart, :estimate, :un_start, :un_finish, :un_deliver
        put :update_category_and_priority
      end
      resources :story_histories

    end
    resources :epics, :controller => :stories
    resources :features, :controller => :stories
    resources :bugs, :controller => :stories
    resources :chores, :controller => :stories
  end

  resources :story_attachments do
    member do
      get :download_attachment
    end
  end

  devise_for :users, :controllers => {:registrations => 'users/registrations'}

  root :to => "dashboard#index"

end

app/models/epic.rb
class Epic < Story
  has_many :stories, :class_name => 'Story', :foreign_key => "epic_id"

  def is_estimatable?
    false
  end

end

app/controllers/epics_controller.rb
class EpicsController < ApplicationController
  # GET /epics
  # GET /epics.xml
  def index
    @project = current_user.projects.find(params[:project])
    @epics = @project.epics

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @epics }
    end
  end

  # GET /epics/1
  # GET /epics/1.xml
  def show
    @epic = Epic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @epic }
    end
  end

  # GET /epics/new
  # GET /epics/new.xml
  def new
    @epic = Epic.new
    @epic.project = current_user.projects.find(params[:project])
    @epic.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @epic }
    end
  end

  # GET /epics/1/edit
  def edit
    @epic = Epic.find(params[:id])
  end

  # POST /epics
  # POST /epics.xml
  def create
    @epic = Epic.new(params[:epic])

    respond_to do |format|
      if @epic.save
        format.html { redirect_to(project_path(@epic.project), :notice => 'Epic was successfully created.') }
        format.xml { render :xml => @epic, :status => :created, :location => @epic }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @epic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /epics/1
  # PUT /epics/1.xml
  def update
    @epic = Epic.find(params[:id])

    respond_to do |format|
      if @epic.update_attributes(params[:epic])
        format.html { redirect_to(project_path(@epic.project),  :notice => 'Epic was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @epic.errors, :status => :unprocessable_entity }
      end
    end
  end

  def finish
    @epic = Epic.find(params[:id])

    respond_to do |format|
      if @epic.finish!
        format.html { redirect_to(project_url(@epic.project), :notice => 'Epic was successfully finished.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @epic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /epics/1
  # DELETE /epics/1.xml
  def destroy
    @epic = Epic.find(params[:id])
    project = @epic.project
    @epic.destroy

    respond_to do |format|
      format.html { redirect_to(project_path(project), :notice => 'Epic was successfully deleted.') }
      format.xml { head :ok }
    end
  end
end

app/views/epics/_epics_collection.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Project</th>
    <th>Status</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% epics.each do |epic| %>
      <tr>
        <td><%= epic.title %></td>
        <td><%= epic.description %></td>
        <td><%= epic.project.name %></td>
        <td><%= epic.status %></td>
        <td><%= epic.user.email %></td>
        <td><%= link_to 'Show', epic %></td>
        <td><%= link_to 'Edit', edit_epic_path(epic) %></td>
        <td><%= link_to 'Destroy', epic, :confirm => 'Are you sure?', :method => :delete %></td>

      </tr>
  <% end %>
</table>

app/views/epics/_form.html.erb
<%= form_for(@epic) do |f| %>
  <% if @epic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@epic.errors.count, "error") %> prohibited this epic from being saved:</h2>

      <ul>
      <% @epic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
    <%= f.hidden_field :project_id %>
    <%= f.hidden_field :status %>
    <%= f.hidden_field :user_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/epics/edit.html.erb
<h1>Editing epic</h1>

<%= render 'form' %>

<%= link_to 'Show', @epic %> |
<%= link_to 'Cancel', project_path(@epic.project) %>

app/views/epics/index.html.erb
<h1>Listing epics</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Project</th>
    <th>Status</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @epics.each do |epic| %>
  <tr>
    <td><%= epic.title %></td>
    <td><%= epic.description %></td>
    <td><%= epic.project.name %></td>
    <td><%= epic.status %></td>
    <td><%= epic.user.email %></td>
    <td><%= link_to 'Show', epic %></td>
    <td><%= link_to 'Edit', edit_epic_path(epic) %></td>
    <td><%= link_to 'Destroy', epic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Epic', new_epic_path %>

app/views/epics/new.html.erb
<h1>New epic</h1>

<%= render 'form' %>

<%= link_to 'Back', epics_path %>

app/views/epics/show.html.erb
<h1><%= @epic.project.name %> : Epic</h1>
<p>
  <b>Title:</b>
  <%= @epic.title %>
</p>

<p>
  <b>Description:</b>
  <%= @epic.description %>
</p>

<p>
  <b>Project:</b>
  <%= @epic.project.name %>
</p>

<p>
  <b>Status:</b>
  <%= @epic.status %>
</p>

<p>
  <b>User:</b>
  <%= @epic.user.email %>
</p>

<% @epic.stories.each do |story| %>
    <%= render :partial => 'stories/story', :locals => {:story => story} %>
<% end %>

<%= link_to 'Edit', edit_epic_path(@epic) %> |
<%= link_to 'Back', project_path(@epic.project) %>
<% if !@epic.finished? %>
    | <%= link_to "Break it Down", new_story_path(:project => @epic.project, :epic => @epic, :type => "Feature") %>
    | <%= link_to "Finish Epic", finish_epic_path(@epic) %>
<% end %>